In [2]:
# Creating an ndarray
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print (arr)
print (type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# 0-D arrays
import numpy as np
arr = np.array(42)
print (arr)

42


In [4]:
# 1-D arrays
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print (arr)

[1 2 3 4 5]


In [6]:
# 2-D arrays
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print (arr)

[[1 2 3]
 [4 5 6]]


In [8]:
# Creating a 3-D arrays with two 2-D arrays
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print (arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [9]:
# ndim attribute to tell us how many dimension the array has
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3],[4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print (a.ndim)
print (b.ndim)
print (c.ndim)
print (d.ndim)

0
1
2
3


In [ ]:
# Accessing 1-D Array Elements
# 0-based indexing
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print (arr[0])
print (arr[1])

1
2


In [11]:
# Accessing 2-D Arrays
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print ('2nd element on 1st row:', arr[0, 1])

2nd element on 1st row: 2


In [ ]:
# Slicing elements from a given index to another index
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print (arr[1:5])

[2 3 4 5]


In [13]:
# Slicing elements from the 0th index to a particular index
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
print (arr[:5])

[1 2 3 4 5]


In [14]:
# Slicing elements from a particular index to last element
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print (arr[4:])

[5 6 7 8]


In [17]:
# Slicing when starting and ending index both aren't mentioned
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9 ,10])
print (arr[:])

[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
# Negative Indexing
import numpy
arr = numpy.array([1, 2, 3, 4, 5, 6, 7])
print (arr[-3:-1])

[5 6]


In [20]:
# Slicing with steps
import numpy
arr = numpy.array([1, 2, 3, 4, 5, 6, 7])
print (arr[1:5:2])

[2 4]


In [21]:
# Slicing with steps without mentioning starting and ending index
import numpy
arr = numpy.array([1, 2, 3, 4, 5, 6, 7])
print (arr[::2])

[1 3 5 7]


In [1]:
# Slicing 2-D arrays
import numpy
arr = numpy.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print (arr[1, 1:4])

[7 8 9]


In [ ]:
# DIY Example 1
import numpy
arr = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = arr[1, 2] # Selects the element at row index 1, column index 2, that is 6!
print (element)

6


In [ ]:
# DIY Example 2
import numpy
arr = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_slice = arr[0:2, : ] # Selects rows with index 0 and 1, all columns
print (row_slice)
# 0:2 indicates rows from index 0 up to (but not including) index 2
# : in the column position means all columns

[2 5]


In [6]:
# DIY Example 3
import numpy
arr = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
col_slice = arr[:, 1:3] # Selects all rows, colums with index 1 and 2
print (col_slice)
# : in the row position means select all rows
# 1:3 indicates columns from index 1 up to (but not including) index 3

[[2 3]
 [5 6]
 [8 9]]
